name: PlatformIO CI Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Test project, fetching dependencies along the way
        run: |
          LD_LIBRARY_PATH=~/.platformio/packages/tool-simavr/lib \
            pio test \
            --project-conf ci-platformio.ini \
            -v \
            --without-uploading
